# Generated by Django 3.1.6 on 2021-02-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0004_auto_20210222_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
