# Generated by Django 3.1.6 on 2021-02-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0006_auto_20210222_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'user'), ('3', 'manager')], max_length=50, null=True),
        ),
    ]
