# Generated by Django 3.1.6 on 2021-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0007_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('female', 'female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('manager', 'manager')], default=None, max_length=50, null=True),
        ),
    ]
