# Generated by Django 3.1.6 on 2021-02-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0008_auto_20210224_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
