# Generated by Django 3.1.6 on 2021-03-05 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='usertask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('blog', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(max_length=250, null=True)),
                ('status', models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('OK', 'OK'), ('BAD', 'BAD')], max_length=50, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('vote', models.IntegerField(default=0)),
                ('subtask', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='managetask.usertask')),
            ],
        ),
    ]
