# Generated by Django 3.1.6 on 2021-03-05 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managetask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managetask.usertask'),
        ),
    ]
