# Generated by Django 3.1.6 on 2021-03-05 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managetask', '0005_auto_20210305_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='managetask.usertask'),
        ),
    ]
